language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
before_script:
    - cd examples/basic
script:
    - pio run
